# docker-compose.yml
services:
  # Frontend React
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: clima-mt-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    networks:
      - clima-network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clima-mt-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - REDIS_HOST=redis
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
      - redis
    networks:
      - clima-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: clima-mt-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-strongpassword}
      - MYSQL_DATABASE=${DB_NAME:-firewatch}
      - MYSQL_USER=${DB_USER:-climauser}
      - MYSQL_PASSWORD=${DB_PASSWORD:-strongpassword}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clima-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: clima-mt-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass}
    volumes:
      - redis-data:/data
    networks:
      - clima-network
    restart: unless-stopped

  # Nginx (opcional - para produção)
  nginx:
    image: nginx:alpine
    container_name: clima-mt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - clima-network
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:

networks:
  clima-network:
    driver: bridge
